### ISSUE TITLE
Error: Firestore isn't installed. Did you forget to `import '@firebase/firestore'`?

### ISSUE THREAD

**Issue by kilroy05** [n6g7/redux-saga-firebase#183]
Hi,

Thanks for making this project open source. Greatly appreciated!
I hope it's not me being silly, but I am getting this error

```utils.js?12fe:225 uncaught at daySaga at daySaga 
 at syncSaga 
 TypeError: rsf.app.firestore is not a function
    at getCollectionRef (webpack-internal:///./node_modules/redux-saga-firebase/dist/firestore.js:47:50)
    at ReduxSagaFirebase.channel (webpack-internal:///./node_modules/redux-saga-firebase/dist/firestore.js:84:37)
    at syncSaga$ (webpack-internal:///./app/containers/Day/saga.js:192:91)
    at tryCatch (webpack-internal:///./node_modules/redux-saga-firebase/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/redux-saga-firebase/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (webpack-internal:///./node_modules/redux-saga-firebase/node_modules/regenerator-runtime/runtime.js:97:21)
    at next (webpack-internal:///./node_modules/redux-saga/es/internal/proc.js:321:27)
    at proc (webpack-internal:///./node_modules/redux-saga/es/internal/proc.js:280:3)
    at runForkEffect (webpack-internal:///./node_modules/redux-saga/es/internal/proc.js:564:19)
    at runEffect (webpack-internal:///./node_modules/redux-saga/es/internal/proc.js:445:800)
```

I am already using firestore, but would like to use this library rather than doing everything myself.
I've started the project using react-boilerplate.
My app is started like this:
```
import app from 'firebase/app';
import 'firebase/auth';
import 'firebase/firestore';

const config = {...}

// Using a class since I am (still but want to get rid of) a firebase HOC
class Firebase {
  constructor() {
    app.initializeApp(config);

    this.auth = app.auth();
    this.db = app.firestore();
//...
//...

// In another file
const firebase = new Firebase();

export const reduxSagaFirebase = new ReduxSagaFirebase(firebase);
```

I am using a Windows machine (not sure if it makes a difference, I'll try my Linux machine tomorrow as it's almost 23 for me :) )

**Comment by kilroy05** [comment]
Alright, so I've given it a go with a new installation and looked into it more clearly.
My implementation of a new Firebase class / HoC isn't the same as `firebase.initializeApp`, so it seems to work ok if instantiation is done outside the object.
In essence: `const myFirebase = app.initializeApp(config);`
And then while I still need to use (getting rid of, I think) my custom implementation with custom methods, pass that in to my custom class
`const firebase = new Firebase(myFirebase);`
So, it was my usage and it seems to be working fine :)

**Comment by Mihai-github** [comment]
Hi @crisrat, I am facing the same issue getting the error for signInWithCredential the following error:

How did you solve the problem???

 
**TypeError: this.app.auth is not a function
    at ReduxSagaFirebase.signInWithCredential$ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.uitt&modulesOnly=false&runModule=true:284404:29)
    at tryCatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.uitt&modulesOnly=false&runModule=true:1440:19)
    at Generator.invoke [as _invoke] (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.uitt&modulesOnly=false&runModule=true:1610:24)
    at Generator.next (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.uitt&modulesOnly=false&runModule=true:1482:23)
    at next (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.uitt&modulesOnly=false&runModule=true:237146:29)
    at proc (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.uitt&modulesOnly=false&runModule=true:237124:5)
    at runCallEffect (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.uitt&modulesOnly=false&runModule=true:236620:9)
    at runEffect (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.uitt&modulesOnly=false&runModule=true:237175:9)
    at digestEffect (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.uitt&modulesOnly=false&runModule=true:237231:7)
    at next (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.uitt&modulesOnly=false&runModule=true:237150:11)**

**Comment by ghost** [comment]
@Mihai-github salutare. de unde?
Don't think I ever got it to work, if memory serves me right. I think I just stopped using that package. I'd guess by now, perhaps they fixed it?

**Comment by Mihai-github** [comment]
@crisrat Salut.

I get this error when calling:

```
const { data } = yield call(
      reduxSagaFirebase.auth.signInWithEmailAndPassword,
      payload.email,
      payload.password
);
```

And I have initialized the ReduxSagaFirebase using:

`export const reduxSagaFirebase = new ReduxSagaFirebase(fbConfig);`

From what I read in the docs this looked like a good way to use redux saga with firebase because I intend to use it with FireStore and this lib seems to have an option to listen to firestore changes using:

`const channel = rsf.firestore.channel('todos');`

Any Idea how can I make this, or other options, to make what I am trying to achieve?

**Comment by ghost** [comment]
@Mihai-github Wish I could help, but not sure.
I stopped using that library long ago - sagas were an overkill for my project back then as well. perhaps they are for you too?

**Comment by Mihai-github** [comment]
Can we talk on some other platform like idk discord? Btw esti roman corect? :))

**Comment by ghost** [comment]
@Mihai-github da, sunt
yeah, I guess

**Comment by Mihai-github** [comment]
Can you add me? 
My discord id is: Darth Vader 2.0#0565

**Comment by ghost** [comment]
@Mihai-github not sure I have discord, but yeah, will check

**Comment by Mihai-github** [comment]
Thank you, if you want we can have a chat on another platform as well.

**Comment by ghost** [comment]
@Mihai-github I don't think that id you sent is right

**Comment by Mihai-github** [comment]
Give me yours and i will add you.

**Comment by ghost** [comment]
@Mihai-github  Chris Griffin#1517

**Comment by Mihai-github** [comment]
Sent
